/*
 * modules.c --- automatically generated by Apache
 * configuration script.  DO NOT HAND EDIT!!!!!
 */

#include "ap_config.h"
#include "httpd.h"
#include "http_config.h"

extern module core_module;
extern module authn_file_module;
extern module authn_core_module;
extern module authz_host_module;
extern module authz_groupfile_module;
extern module authz_user_module;
extern module authz_core_module;
extern module access_compat_module;
extern module auth_basic_module;
extern module so_module;
extern module reqtimeout_module;
extern module filter_module;
extern module http_module;
extern module mime_module;
extern module log_config_module;
extern module env_module;
extern module headers_module;
extern module setenvif_module;
extern module version_module;
extern module mpm_event_module;
extern module unixd_module;
extern module status_module;
extern module autoindex_module;
extern module dir_module;
extern module alias_module;

/*
 *  Modules which implicitly form the
 *  list of activated modules on startup,
 *  i.e. these are the modules which are
 *  initially linked into the Apache processing
 *  [extendable under run-time via AddModule]
 */
module *ap_prelinked_modules[] = {
  &core_module,
  &authn_file_module,
  &authn_core_module,
  &authz_host_module,
  &authz_groupfile_module,
  &authz_user_module,
  &authz_core_module,
  &access_compat_module,
  &auth_basic_module,
  &so_module,
  &reqtimeout_module,
  &filter_module,
  &http_module,
  &mime_module,
  &log_config_module,
  &env_module,
  &headers_module,
  &setenvif_module,
  &version_module,
  &mpm_event_module,
  &unixd_module,
  &status_module,
  &autoindex_module,
  &dir_module,
  &alias_module,
  NULL
};

/*
 *  We need the symbols as strings for <IfModule> containers
 */

ap_module_symbol_t ap_prelinked_module_symbols[] = {
  {"core_module", &core_module},
  {"authn_file_module", &authn_file_module},
  {"authn_core_module", &authn_core_module},
  {"authz_host_module", &authz_host_module},
  {"authz_groupfile_module", &authz_groupfile_module},
  {"authz_user_module", &authz_user_module},
  {"authz_core_module", &authz_core_module},
  {"access_compat_module", &access_compat_module},
  {"auth_basic_module", &auth_basic_module},
  {"so_module", &so_module},
  {"reqtimeout_module", &reqtimeout_module},
  {"filter_module", &filter_module},
  {"http_module", &http_module},
  {"mime_module", &mime_module},
  {"log_config_module", &log_config_module},
  {"env_module", &env_module},
  {"headers_module", &headers_module},
  {"setenvif_module", &setenvif_module},
  {"version_module", &version_module},
  {"mpm_event_module", &mpm_event_module},
  {"unixd_module", &unixd_module},
  {"status_module", &status_module},
  {"autoindex_module", &autoindex_module},
  {"dir_module", &dir_module},
  {"alias_module", &alias_module},
  {NULL, NULL}
};

/*
 *  Modules which initially form the
 *  list of available modules on startup,
 *  i.e. these are the modules which are
 *  initially loaded into the Apache process
 *  [extendable under run-time via LoadModule]
 */
module *ap_preloaded_modules[] = {
  &core_module,
  &authn_file_module,
  &authn_core_module,
  &authz_host_module,
  &authz_groupfile_module,
  &authz_user_module,
  &authz_core_module,
  &access_compat_module,
  &auth_basic_module,
  &so_module,
  &reqtimeout_module,
  &filter_module,
  &http_module,
  &mime_module,
  &log_config_module,
  &env_module,
  &headers_module,
  &setenvif_module,
  &version_module,
  &mpm_event_module,
  &unixd_module,
  &status_module,
  &autoindex_module,
  &dir_module,
  &alias_module,
  NULL
};

